version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      MONGO_URI: mongodb://db:27017/movies
  db:
    image: mongo
    ports:
      - "27017:27017"
